package modelo;
// Generated 11 dic. 2018 14:13:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Campo generated by hbm2java
 */
public class Campo  implements java.io.Serializable {


     private int idcampo;
     private String nombrecampo;
     private double superficiecampo;
     private String estadocampo;
     private Set lotes = new HashSet(0);

    public Campo() {
    }

	
    public Campo(int idcampo, String nombrecampo, double superficiecampo) {
        this.idcampo = idcampo;
        this.nombrecampo = nombrecampo;
        this.superficiecampo = superficiecampo;
    }
    public Campo(int idcampo, String nombrecampo, double superficiecampo, String estadocampo, Set lotes) {
       this.idcampo = idcampo;
       this.nombrecampo = nombrecampo;
       this.superficiecampo = superficiecampo;
       this.estadocampo = estadocampo;
       this.lotes = lotes;
    }
   
    public int getIdcampo() {
        return this.idcampo;
    }
    
    public void setIdcampo(int idcampo) {
        this.idcampo = idcampo;
    }
    public String getNombrecampo() {
        return this.nombrecampo;
    }
    
    public void setNombrecampo(String nombrecampo) {
        this.nombrecampo = nombrecampo;
    }
    public double getSuperficiecampo() {
        return this.superficiecampo;
    }
    
    public void setSuperficiecampo(double superficiecampo) {
        this.superficiecampo = superficiecampo;
    }
    public String getEstadocampo() {
        return this.estadocampo;
    }
    
    public void setEstadocampo(String estadocampo) {
        this.estadocampo = estadocampo;
    }
    public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }

    @Override
    public String toString() {
        return "Campo{" + "idcampo=" + idcampo + ", nombrecampo=" + nombrecampo + ", superficiecampo=" + superficiecampo + ", estadocampo=" + estadocampo + ", lotes=" + lotes + '}';
    }

    public void agregarLote(Lote lote) {
        lotes.add(lote);
    }




}


